name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no xx-user-xx@xx-server-ip-xx << 'EOF'
            cd /home/raven/tests/invoice-generation/invoice-generation

            # Stop the Docker container
            sudo make stop-app-invoice-generation 

            # Pull the latest changes from the master branch
            git pull origin master

            # Build the Container
            sudo make build-app-invoice-generation

            # Start the Docker container
            sudo make run-app-invoice-generation
          EOF
